INSERT INTO dbo.HERO (FIRST_NAME,LAST_NAME,APPEARED,FOUNDER)
SELECT 'Mickey','Mouse','1928-05-15','Disney'
GO
INSERT INTO dbo.HERO (FIRST_NAME,LAST_NAME,APPEARED,FOUNDER)
SELECT 'Donald', 'Duck', '1934-06-09','Disney'
GO
INSERT INTO dbo.HERO (FIRST_NAME,LAST_NAME,APPEARED,FOUNDER)
SELECT 'Johnny', 'Bravo', '1997-07-14','Warner Bros.'
GO
