IF OBJECT_ID('dbo.HERO' , 'U') IS NULL
CREATE TABLE dbo.HERO
(
  HERO_ID INT IDENTITY(1,1),
  FIRST_NAME NVARCHAR(50) NOT NULL,
  LAST_NAME NVARCHAR(50) NOT NULL,
  APPEARED DATE NULL ,
  FOUNDER NVARCHAR(50) NOT NULL DEFAULT '' ,
  IS_ACTIVE BIT NOT NULL DEFAULT 1,
  CONSTRAINT PK_HERO PRIMARY KEY (HERO_ID),
  CONSTRAINT UQ_HERO_LAST_NAME_FIRST_NAME UNIQUE (LAST_NAME , FIRST_NAME)
)
;
